name: GitHub Actions 
run-name: ${{ github.actor }} test
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Docker build image  
      run: docker build -t logger .

    - name: Run docker
      run: |
        echo Docker worked succesfully. Success! | docker run -i -v "$(pwd)/logs/:/home/logs/" logger

    - name: logs1
      run: |
        docker inspect logger

    - name: logs2
      run: |
        cat logs/log.txt

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/
